# Y = run this demo
# S = skip this demo
# Other processes can directly modify these items to control the scope of this execution.
gemma3=Y
LiquidAI-LFM2.5-230M=Y
moonshine=Y
moonshine_streaming=Y
LiquidAI-LFM2-VL-450M=Y
object_detection=Y
pose_estimation=Y
